-- Drop all triggers
DROP TRIGGER IF EXISTS delete_file_trigger ON files;

-- Drop all functions
DROP FUNCTION IF EXISTS delete_physical_file();

-- Drop all tables
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS help_requests CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS main_categories CASCADE; 